language: python
python:
   - 3.5
   - 3.6
install:
   - pip install tifffile==2019.7.26
   - pip install -r requirements.txt
   - pip install nose
script:
   - pip install --editable .
   - nosetests tests
   - tsv-convert-2d-tif --help
   - tsv-simple-convert-2d-tif --help
   - tsv-renumber --help
   - tsv-renumber-directories --help
   - tsv-fill-blanks --help
   - tsv-downsample --help
sudo: false
